import Head from "next/head";
import React, { useEffect, useState } from "react";
import About2 from "../components/about/About2";
import Banner2 from "../components/banner/Banner2";
import Home2Blog from "../components/blog/Home2Blog";
import InstagramFeed from "../components/common/InstagramFeed";
import Preloader from "../components/common/Preloader";
import Home2Counter from "../components/countdown/Home2Counter";
import Home2Feature from "../components/feature/Home2Feature";
import Footer1 from "../components/footer/Footer1";
import Header2 from "../components/header/Header2";
import Home2Offer from "../components/offer/Home2Offer";
import Home2Package2 from "../components/package/Home2Package2";
import Home2Testimonial from "../components/testimonial/Home2Testimonial";
import Home2Tourplan from "../components/tourPlan/Home2Tourplan";

function IndexTravel2() {
  const [loading, setLoading] = useState(false);
  useEffect(() => {
    setLoading(false);
    setTimeout(() => {
      setLoading(true);
    }, 3000);
  }, []);
  return (
    <>
      {!loading ? (
        <>
        <Head>
        <title>Loading</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="assets/images/icons/logo-icon.svg" />
      </Head>
        <Preloader loader="home2preloader" />
        </>
      ) : (
        <>
        <Head>
        <title>Astrip - Tour Booking and Travel Agency React NextJS Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="assets/images/icons/logo-icon.svg" />
      </Head>
          <Header2 />
          <Banner2 />
          <About2 />
          <Home2Offer />
          <Home2Package2 />
          <Home2Counter />
          <Home2Tourplan />
          <Home2Feature />
          <Home2Blog />
          <Home2Testimonial />
          <InstagramFeed />
          <Footer1 />
        </>
      )}
    </>
  );
}

export default IndexTravel2;
